### ISSUE TITLE
Used on server 1.19.2 will be kicked off the server!

### ISSUE THREAD

**Issue by Memories-white** [Giggitybyte/ServerChatHistory#4]
If you log in to the server for the first time, you can send the content normally. If you log out and re-join the server, the sent messages will be kicked out of the server. You need to disable message verification before you can use the server normally

**Comment by Memories-white** [comment]
When kicked off the server, the message cannot be verified!

**Comment by Giggitybyte** [comment]
Cannot reproduce this on v1.4.0.
